4411403 (1/99): CT
4411403 (1/99): DRR
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
219
4411403 (1/99): DRR (pos)
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
4411403 (1/99): FBP
FBP:   0%|          | 0/400 [00:00<?, ?it/s]
4411403 (1/99): FBP (pos)
FBP:   0%|          | 0/350 [00:00<?, ?it/s]
4411403 (1/99): Resize
Resize:   0%|          | 0/50 [00:00<?, ?it/s]
4411398 (2/99): CT
4411398 (2/99): DRR
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
214
4411398 (2/99): DRR (pos)
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mfujita/Documents/research/prepare.py", line 43, in <module>
    main()
  File "/home/mfujita/Documents/research/prepare.py", line 31, in main
    p = patient.patient(
  File "/home/mfujita/Documents/research/patient/patient.py", line 83, in __init__
    self.generate_posdrr()
  File "/home/mfujita/Documents/research/patient/patient.py", line 154, in generate_posdrr
    cropstartx=cropstartx, cropstarty=cropstarty,
  File "/home/mfujita/Documents/research/drr/drr.py", line 101, in __init__
    img_tensor = drr(**detector_kwargs)
  File "/home/mfujita/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mfujita/Documents/research/drr/DiffDRR/diffdrr/drr.py", line 91, in forward
    drr = self.siddon.raytrace(source, rays)
  File "/home/mfujita/Documents/research/drr/DiffDRR/diffdrr/projectors/siddon.py", line 77, in raytrace
    voxels = self.get_voxel(alphamid, source, target)
  File "/home/mfujita/Documents/research/drr/DiffDRR/diffdrr/projectors/siddon.py", line 62, in get_voxel
    idxs = (
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.04 GiB (GPU 0; 11.76 GiB total capacity; 4.99 GiB already allocated; 1.04 GiB free; 5.60 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
4411433 (3/99): CT
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
228
4411433 (3/99): DRR
4411433 (3/99): DRR (pos)
Traceback (most recent call last):
  File "/home/mfujita/Documents/research/prepare.py", line 43, in <module>
    main()
  File "/home/mfujita/Documents/research/prepare.py", line 31, in main
    p = patient.patient(
  File "/home/mfujita/Documents/research/patient/patient.py", line 83, in __init__
    self.generate_posdrr()
  File "/home/mfujita/Documents/research/patient/patient.py", line 156, in generate_posdrr
    delx=delx, zm=zm, adjust=False)
NameError: name 'zm' is not defined
4411396 (4/99): CT
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
212
4411396 (4/99): DRR
4411396 (4/99): DRR (pos)
Traceback (most recent call last):
  File "/home/mfujita/Documents/research/prepare.py", line 43, in <module>
    main()
  File "/home/mfujita/Documents/research/prepare.py", line 31, in main
    p = patient.patient(
  File "/home/mfujita/Documents/research/patient/patient.py", line 83, in __init__
    self.generate_posdrr()
  File "/home/mfujita/Documents/research/patient/patient.py", line 156, in generate_posdrr
    cropheight=cropheight, cropwidth=cropwidth,
NameError: name 'zm' is not defined
4411471 (6/99): CT
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
219
4411471 (6/99): DRR
4411471 (6/99): DRR (pos)
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
4411471 (6/99): FBP
FBP:   0%|          | 0/400 [00:00<?, ?it/s]
4411471 (6/99): FBP (pos)
FBP:   0%|          | 0/350 [00:00<?, ?it/s]
4411471 (6/99): Resize
Resize:   0%|          | 0/50 [00:00<?, ?it/s]
4411564 (7/99): CT
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
220
4411564 (7/99): DRR
4411564 (7/99): DRR (pos)
DRR:   0%|          | 0/450 [00:00<?, ?it/s]
4411564 (7/99): FBP
